version: '3.9'
services:
  web:
    build: .
    env_file:
      - .env
    # Override values in .env
    environment:
      - PORT=${CONTAINER_PORT}
    ports:
      - '127.0.0.1:${CONTAINER_PORT}:${CONTAINER_PORT}'
    networks:
      - mongodb
    stdin_open: true # docker run -i
    tty: true        # docker run -t

networks:
  mongodb:
    name: mongodb_default
    external: true
